# Cyberpunk-inspired Alacritty Configuration

# Colors
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#1C1C2C"
red = "#FF0000"
green = "#00FF00"
yellow = "#FFA500"
blue = "#00FFFF"
magenta = "#FF00FF"
cyan = "#00FFFF"
white = "#F0F0F0"

[colors.cursor]
text = "#0C0C1E"
cursor = "#00FFFF"

[colors.normal]
black = "#0C0C1E"
red = "#FF1493"
green = "#00FF00"
yellow = "#FFA500"
blue = "#1E90FF"
magenta = "#FF00FF"
cyan = "#00FFFF"
white = "#D7D7D5"

[colors.primary]
background = "#0C0C1E"
foreground = "#00FFFF"

[cursor]
style = "Beam"

[env]
TERM = "alacritty"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 3
y = 2

[scrolling]
history = 99999

[selection]
save_to_clipboard = true

[shell]
program = "/bin/bash"
args = ["-ilc", "source ~/.bash_functions && start_zellij"]

[window]
opacity = 0.98

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 8
y = 4