[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#54ced6"
green = "#9ec400"
magenta = "#b77ee0"
red = "#ff3334"
white = "#2a2a2a"
yellow = "#e7c547"

[colors.normal]
black = "#000000"
blue = "#7aa6da"
cyan = "#70c0ba"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#424242"
yellow = "#e6c547"

[colors.primary]
background = "#000000"
foreground = "#eaeaea"

[cursor]
style = "Beam"

[env]
TERM = "alacritty"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 3
y = 2

[scrolling]
history = 99999

[selection]
save_to_clipboard = true

[shell]
program = "/bin/bash"
args = ["-ilc", "source ~/.bash_functions && start_zellij"]

[window]
opacity = 0.98

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 8
y = 4

