# Cyberpunk-inspired Alacritty Configuration

# Colors
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#1a1a38"
red = "#ff1744"
green = "#39ff14"
yellow = "#ffea00"
blue = "#1e90ff"
magenta = "#d500f9"
cyan = "#00e5ff"
white = "#e6ffcc"

[colors.cursor]
text = "#0c0c1e"
cursor = "#00e5ff"

[colors.normal]
black = "#0c0c1e"
red = "#ff1744"
green = "#39ff14"
yellow = "#ffea00"
blue = "#1e90ff"
magenta = "#d500f9"
cyan = "#00e5ff"
white = "#b0bec5"

[colors.primary]
background = "#0c0c1e"
foreground = "#39ff14"

[cursor]
style = "Beam"

[env]
TERM = "alacritty"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 3
y = 2

[scrolling]
history = 99999

[selection]
save_to_clipboard = true

[shell]
program = "/bin/bash"
args = ["-ilc", "source ~/.bash_functions && start_zellij"]

[window]
opacity = 0.98

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 8
y = 4
