# colors from https://github.com/eendroroy/alacritty-theme/blob/master/themes/cyber_punk_neon.yaml
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x1c61c2"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x00ff00"
magenta = "0x711c91"
cyan = "0x0abdc6"
white = "0xd7d7d5"

[colors.cursor]
text = "0x000b1e"
cursor = "0x0abdc6"

[colors.normal]
black = "0x123e7c"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x123e7c"
cyan = "0x0abdc6"
magenta = "0x711c91"
white = "0xd7d7d5"

[colors.primary]
background = "0x000b1e"
foreground = "0x0abdc6"

[cursor]
style = "Beam"

[env]
TERM = "alacritty"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 3
y = 2

[scrolling]
history = 99999

[selection]
save_to_clipboard = true

[shell]
program = "/bin/bash"
args = ["-ilc", "source ~/.bash_functions && start_zellij"]

[window]
opacity = 0.98

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 8
y = 4
